<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="28" started-at="2017-12-04T00:16:38Z" finished-at="2017-12-04T00:16:38Z">
    <groups>
      <group name="checkintest">
        <method signature="GroupTestExample.testPrintMessage()[pri:0, instance:TestNG.GroupTestExample@28feb3fa]" name="testPrintMessage" class="TestNG.GroupTestExample"/>
      </group> <!-- checkintest -->
      <group name="functest">
        <method signature="GroupTestExample.testPrintMessage()[pri:0, instance:TestNG.GroupTestExample@28feb3fa]" name="testPrintMessage" class="TestNG.GroupTestExample"/>
        <method signature="GroupTestExample.testingExitMessage()[pri:0, instance:TestNG.GroupTestExample@28feb3fa]" name="testingExitMessage" class="TestNG.GroupTestExample"/>
      </group> <!-- functest -->
    </groups>
    <test name="test1" duration-ms="28" started-at="2017-12-04T00:16:38Z" finished-at="2017-12-04T00:16:38Z">
      <class name="TestNG.GroupTestExample">
        <test-method status="PASS" signature="testPrintMessage()[pri:0, instance:TestNG.GroupTestExample@28feb3fa]" name="testPrintMessage" duration-ms="9" started-at="2017-12-04T08:16:38Z" finished-at="2017-12-04T08:16:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrintMessage -->
        <test-method status="FAIL" signature="testingExitMessage()[pri:0, instance:TestNG.GroupTestExample@28feb3fa]" name="testingExitMessage" duration-ms="1" started-at="2017-12-04T08:16:38Z" finished-at="2017-12-04T08:16:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [www..com] but found [wwwtutorialspoit.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [www..com] but found [wwwtutorialspoit.com]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at TestNG.GroupTestExample.testingExitMessage(GroupTestExample.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testingExitMessage -->
      </class> <!-- TestNG.GroupTestExample -->
    </test> <!-- test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
